# Generated by Django 2.2.7 on 2019-11-20 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nyhed')),
                ('date', models.DateField(default=datetime.date(2019, 11, 20), verbose_name='Dato')),
            ],
        ),
    ]
