# Generated by Django 2.2.7 on 2019-11-20 15:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Handicapskydning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 20, 15, 19, 43, 704006, tzinfo=utc), verbose_name='Dato'),
        ),
    ]
