# Generated by Django 2.2.7 on 2019-11-20 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Handicapskydning', '0004_auto_20191120_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 20, 15, 44, 52, 91737, tzinfo=utc), verbose_name='Dato'),
        ),
    ]
