# Generated by Django 2.2.7 on 2019-11-20 15:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Handicapskydning', '0005_auto_20191120_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 20, 15, 49, 23, 175355, tzinfo=utc), verbose_name='Dato'),
        ),
        migrations.AlterModelTable(
            name='news',
            table='Nyheder',
        ),
    ]
