# Generated by Django 2.2.7 on 2019-11-20 15:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Handicapskydning', '0006_auto_20191120_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Nyhed', 'verbose_name_plural': 'Nyheder'},
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 20, 15, 53, 6, 94116, tzinfo=utc), verbose_name='Dato'),
        ),
        migrations.AlterModelTable(
            name='news',
            table=None,
        ),
    ]
