# Generated by Django 2.2.7 on 2019-11-20 17:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Handicapskydning', '0007_auto_20191120_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255, verbose_name='Region')),
                ('city', models.CharField(max_length=255, verbose_name='By')),
                ('rank', models.CharField(max_length=255, verbose_name='Klasse')),
                ('date', models.DateField(default=datetime.datetime(2019, 11, 20, 17, 6, 48, 902547, tzinfo=utc), verbose_name='Dato')),
            ],
            options={
                'verbose_name': 'Aktivitet',
                'verbose_name_plural': 'Aktiviteter',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 20, 17, 6, 48, 901546, tzinfo=utc), verbose_name='Dato'),
        ),
    ]
