# Generated by Django 2.2.7 on 2019-11-20 17:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Handicapskydning', '0009_auto_20191120_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.CharField(max_length=255, verbose_name='Konkurrance')),
                ('link', models.CharField(max_length=2083, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Resultat',
                'verbose_name_plural': 'Resultater',
            },
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 20, 17, 18, 28, 849613, tzinfo=utc), verbose_name='Dato'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 20, 17, 18, 28, 849613, tzinfo=utc), verbose_name='Dato'),
        ),
    ]
