# Generated by Django 2.2.7 on 2019-11-20 18:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Handicapskydning', '0011_auto_20191120_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffmember',
            options={'verbose_name': 'Bestyrelses medlem', 'verbose_name_plural': 'Bestyrelses medlemmer'},
        ),
        migrations.AddField(
            model_name='staffmember',
            name='title',
            field=models.CharField(default='Formand', max_length=510, verbose_name='Titel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 20, 18, 33, 2, 966561, tzinfo=utc), verbose_name='Dato'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 20, 18, 33, 2, 966561, tzinfo=utc), verbose_name='Dato'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Handicapskydning.Department', verbose_name='Afdeling'),
        ),
    ]
