# Generated by Django 2.2.7 on 2019-11-20 18:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Handicapskydning', '0012_auto_20191120_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Navn')),
                ('city', models.CharField(max_length=255, verbose_name='By')),
                ('link', models.URLField(max_length=2083, verbose_name='Hjemmeside')),
            ],
            options={
                'verbose_name': 'Klub',
                'verbose_name_plural': 'Klubber',
            },
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 20, 18, 48, 17, 738406, tzinfo=utc), verbose_name='Dato'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 20, 18, 48, 17, 738406, tzinfo=utc), verbose_name='Dato'),
        ),
    ]
