# Generated by Django 2.2.7 on 2019-11-21 20:19

import Handicapskydning.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Handicapskydning', '0018_auto_20191121_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 21, 20, 19, 14, 330079, tzinfo=utc), verbose_name='Dato'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 21, 20, 19, 14, 330079, tzinfo=utc), verbose_name='Dato'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='profile_image',
            field=models.ImageField(upload_to=Handicapskydning.models.get_profile_picture),
        ),
    ]
