# Generated by Django 2.2.7 on 2019-11-21 20:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Handicapskydning', '0019_auto_20191121_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 21, 20, 20, 9, 50370, tzinfo=utc), verbose_name='Dato'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 21, 20, 20, 9, 49370, tzinfo=utc), verbose_name='Dato'),
        ),
    ]
