# Generated by Django 2.2.7 on 2019-11-24 15:46

import Handicapskydning.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Handicapskydning', '0026_auto_20191124_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Navn')),
                ('picture', models.ImageField(upload_to=Handicapskydning.models.get_link_picture)),
                ('link', models.URLField(max_length=2083, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 24, 15, 46, 40, 584859, tzinfo=utc), verbose_name='Dato'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 24, 15, 46, 40, 583859, tzinfo=utc), verbose_name='Dato'),
        ),
    ]
