# Generated by Django 2.2.7 on 2019-11-24 16:30

import Handicapskydning.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Handicapskydning', '0027_auto_20191124_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Samling')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Årstal')),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 24, 16, 30, 25, 351950, tzinfo=utc), verbose_name='Dato'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 24, 16, 30, 25, 351950, tzinfo=utc), verbose_name='Dato'),
        ),
        migrations.CreateModel(
            name='CPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=Handicapskydning.models.get_collection_image, verbose_name='Biliede')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Handicapskydning.Collections', verbose_name='Samling')),
            ],
        ),
    ]
